#log 配置:显示sql语句，便于debug
logging:
  level:
    cn.edu.zzuli.mapper: DEBUG
#SpringBoot + mybatis
mybatis:
  mapper-locations: classpath*:dao/*Mapper.xml
#DB config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.112.28.98:3306/netshop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: RenYao123!
server:
  servlet-path: /netshop
